/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiMembersRouteImport } from './routes/api/members'
import { Route as ApiKeepaliveRouteImport } from './routes/api/keepalive'
import { Route as AuthenticatedProfessoresRouteImport } from './routes/_authenticated/professores'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMembersRoute = ApiMembersRouteImport.update({
  id: '/api/members',
  path: '/api/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveRoute = ApiKeepaliveRouteImport.update({
  id: '/api/keepalive',
  path: '/api/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfessoresRoute =
  AuthenticatedProfessoresRouteImport.update({
    id: '/professores',
    path: '/professores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/professores': typeof AuthenticatedProfessoresRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/api/members': typeof ApiMembersRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/professores': typeof AuthenticatedProfessoresRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/api/members': typeof ApiMembersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/professores': typeof AuthenticatedProfessoresRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/api/members': typeof ApiMembersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comercial'
    | '/configuracoes'
    | '/financeiro'
    | '/perfil'
    | '/professores'
    | '/api/keepalive'
    | '/api/members'
    | '/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/comercial'
    | '/configuracoes'
    | '/financeiro'
    | '/perfil'
    | '/professores'
    | '/api/keepalive'
    | '/api/members'
    | '/'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/comercial'
    | '/_authenticated/configuracoes'
    | '/_authenticated/financeiro'
    | '/_authenticated/perfil'
    | '/_authenticated/professores'
    | '/api/keepalive'
    | '/api/members'
    | '/_authenticated/'
    | '/_authenticated/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiKeepaliveRoute: typeof ApiKeepaliveRoute
  ApiMembersRoute: typeof ApiMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/members': {
      id: '/api/members'
      path: '/api/members'
      fullPath: '/api/members'
      preLoaderRoute: typeof ApiMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive': {
      id: '/api/keepalive'
      path: '/api/keepalive'
      fullPath: '/api/keepalive'
      preLoaderRoute: typeof ApiKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/professores': {
      id: '/_authenticated/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof AuthenticatedProfessoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProfessoresRoute: typeof AuthenticatedProfessoresRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProfessoresRoute: AuthenticatedProfessoresRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiKeepaliveRoute: ApiKeepaliveRoute,
  ApiMembersRoute: ApiMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
