/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as IndexRouteImport } from './routes/index'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/financeiro': typeof FinanceiroRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/financeiro': typeof FinanceiroRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/financeiro': typeof FinanceiroRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comercial' | '/financeiro' | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comercial' | '/financeiro' | '/perfil'
  id: '__root__' | '/' | '/comercial' | '/financeiro' | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComercialRoute: typeof ComercialRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComercialRoute: ComercialRoute,
  FinanceiroRoute: FinanceiroRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
